public class cinco_num {
 public static void main(String[] args) {

int n1 = Integer.parseInt(IO.readln("Digite o primeiro numero: "));
int n2 = Integer.parseInt(IO.readln("Digite o segundo numero: "));
int n3 = Integer.parseInt(IO.readln("Digite o terceiro numero: "));
int n4 = Integer.parseInt(IO.readln("Digite o quarto numero: "));
int n5 = Integer.parseInt(IO.readln("Digite o quinto numero: "));

IO.println("Numeros digitados");
     IO.println(n1);
     IO.println(n2);
     IO.println(n3);
     IO.println(n4);
     IO.println(n5);

 }

}

