public class tabuada {
    public static void main(String[] args) {

IO.println("*****************************");
float numero_1 = Float.parseFloat(IO.readln("Informe os numeros da tabuada: "));
IO.println("*****************************");

int n1 = (int) (numero_1 * 1);
int n2 = (int) (numero_1 * 2);
int n3 = (int) (numero_1 * 3);
int n4 = (int) (numero_1 * 4);
int n5 = (int) (numero_1 * 5);
int n6 = (int) (numero_1 * 6);
int n7 = (int) (numero_1 * 7);
int n8 = (int) (numero_1 * 8);
int n9 = (int) (numero_1 * 9);
int n10 = (int) (numero_1 * 10);

IO.println(n1);
IO.println(n2);
IO.println(n3);
IO.println(n4);
IO.println(n5);
IO.println(n6);
IO.println(n7);
IO.println(n8);
IO.println(n9);
IO.println(n10);

    }

}

